slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_toolbox_namespace: ""
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    mode: mapping
    resolution: 0.05
    max_laser_range: 10.0

    minimumTimeBetweenGraphOptimizations: 2.0
    maxSubmapsToKeep: 5

    transform_publish_period: 0.05
    map_update_interval: 1.0
    enable_interactive_mode: false
